version: '1'

services:
  app:
    build:
      context: .
      dockerfile: ../Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://0.0.0.0:5432/db_sistemacontasapagar
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: db_sistemacontasapagar
    ports:
      - "5432:5432"
    volumes:
      - ./V1__creeate-tb-conta.sql:/docker-entrypoint-initdb.d/V1__creeate-tb-conta.sql
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
